version: 2.1

executors:
  rust-executor:
    docker:
      - image: rust:latest

jobs:
  check-fmt:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: install rustfmt
          command: rustup component add rustfmt
      - run:
          name: check formatting
          command: cargo fmt -- --check
  build-native:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: build kiss3d
          command: cargo build --verbose -p kiss3d;
      - run:
           name: test kiss3d
           command: RUSTFLAGS="-D warnings" cargo check --all-targets --all-features;
  build-wasm:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: add wasm32 target
          command: rustup target add wasm32-unknown-unknown;
      - run:
          name: build kiss3d
          command: cargo build --verbose --target wasm32-unknown-unknown -p kiss3d;


workflows:
  version: 2
  build:
    jobs:
      - check-fmt
      - build-native:
          requires:
            - check-fmt
      - build-wasm:
          requires:
            - check-fmt
